[package]
name = "gensokyo"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.50"
crossbeam = "0.8.1"
futures = "0.3.16"
thiserror = "1.0.26"
tokio = { version = "1.17.0", features = ["full"] }
